# This rule is not used by the project cex-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cex.cex.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cex-operator
    app.kubernetes.io/managed-by: kustomize
  name: cexplugin-admin-role
rules:
- apiGroups:
  - cex.cex.dev
  resources:
  - cexplugins
  verbs:
  - '*'
- apiGroups:
  - cex.cex.dev
  resources:
  - cexplugins/status
  verbs:
  - get
