# This rule is not used by the project cex-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cex.cex.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cex-operator
    app.kubernetes.io/managed-by: kustomize
  name: cexplugin-viewer-role
rules:
- apiGroups:
  - cex.cex.dev
  resources:
  - cexplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cex.cex.dev
  resources:
  - cexplugins/status
  verbs:
  - get
