apiVersion: cex.cex.dev/v1alpha1
kind: CexPlugin
metadata:
  labels:
    app.kubernetes.io/name: cex-operator
    app.kubernetes.io/managed-by: kustomize
  name: cexplugin-sample
spec:
  # TODO(user): Add fields here
